version: '3.7'

services:
    web:
        build: .
        # command: python /code/manage.py runserver 0.0.0.0:8000
        command: gunicorn records_project.wsgi -b 0.0.0.0:8000
        environment:
            - SECRET_KEY=h#=6(vm+k4o$$9c#8tw=9nj6(*cg3pyg$$3cdfje*_f!gb8g8*c-
            - DEBUG=1
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - EMAIL_HOST=smtp.sendgrid.net
            - EMAIL_HOST_USER=apikey
            - EMAIL_HOST_PASSWORD=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
            - EMAIL_PORT=587
            - EMAIL_USE_TLS=True
            - ENVIRONMENT=development
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:12
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
    postgres_data:
